In [1]:
#| default_exp tests.test_model

In [1]:
#| export
import torch
import torch.nn.functional as f

from fastcore.utils import *
from tinypytorch.core import *
from tinypytorch.model import Lin, ReLU, MSE, initialize_parameters, log_softmax, nll, cross_entropy

import pytest

In [2]:
#| hide
from nbdev.showdoc import *
from fastcore.test import *

#### Tensor for tests

In [3]:
#| export
A = torch.arange(start=-4, end=8, dtype=torch.float)

In [4]:
#| export
A = torch.reshape(A, (4, 3))

In [5]:
A

tensor([[-4., -3., -2.],
        [-1.,  0.,  1.],
        [ 2.,  3.,  4.],
        [ 5.,  6.,  7.]])

In [6]:
#| export
B = torch.arange(13, 25, dtype=torch.float)

In [7]:
#| export
B = torch.reshape(B, (4, 3))

In [8]:
B

tensor([[13., 14., 15.],
        [16., 17., 18.],
        [19., 20., 21.],
        [22., 23., 24.]])

#### Loss Functions

##### Mean Squared Error

In [9]:
#| export
def test_mse_should_return_true():
    
    output = MSE().forward(A, B)
    result = f.mse_loss(A, B)
    
    assert output == result

In [10]:
#| export
def test_mse_gradient_should_return_true():
    pass

##### Cross-entropy Loss

In [11]:
#| export
@pytest.mark.xfail
def test_log_softmax_should_return_true():
    assert torch.equal(log_softmax(A), f.log_softmax(A, dim=1)) == True

In [12]:
torch.equal(log_softmax(A), f.log_softmax(A, dim=1))

False

In [13]:
torch.eq(log_softmax(A), f.log_softmax(A, dim=1))

tensor([[ True,  True, False],
        [ True,  True, False],
        [ True,  True, False],
        [ True,  True, False]])

In [14]:
log_softmax(A)

tensor([[-2.4076, -1.4076, -0.4076],
        [-2.4076, -1.4076, -0.4076],
        [-2.4076, -1.4076, -0.4076],
        [-2.4076, -1.4076, -0.4076]])

In [15]:
assert log_softmax(A) == log_softmax(A)

RuntimeError: Boolean value of Tensor with more than one value is ambiguous

In [ ]:
f.log_softmax(A, dim=1)

In [ ]:
log_softmax(A) == f.log_softmax(A, dim=1)

In [ ]:
log_softmax(A) == log_softmax(A)

##### Negative Log Likelihood

In [42]:
#| export
def test_nll_should_return_true():
    
    targ = torch.tensor([1, 0])
    sm_pred = torch.tensor([[0, 1, 2], [5, 0, 4]], dtype=torch.float)
    
    assert nll(sm_pred, targ) == -3.

##### Cross-entropy Loss

In [47]:
pred = torch.tensor([[0, 1, 2], [5, 0, 4]], dtype=torch.float)

In [48]:
targ = torch.tensor([2, 1])

In [51]:
result = f.cross_entropy(pred, targ)

In [52]:
result

tensor(2.8629)

In [53]:
#| export
def test_cross_entropy_loss():
    pred = torch.tensor([[0, 1, 2], [5, 0, 4]], dtype=torch.float)
    targ = torch.tensor([2, 1])
    
    assert cross_entropy(pred, targ) == f.cross_entropy(pred, targ)

#### Activation Functions

In [40]:
#| export
@pytest.mark.xfail
def test_relu_should_return_true():
    
    output = ReLU().forward(A)
    result = f.relu(A) - 0.5
    assert output == result

In [245]:
#| export
def test_relu_gradient_should_return_true():
    pass

In [210]:
output = ReLU().forward(A)

In [211]:
output

tensor([[-0.5000, -0.5000, -0.5000],
        [-0.5000, -0.5000,  0.5000],
        [ 1.5000,  2.5000,  3.5000],
        [ 4.5000,  5.5000,  6.5000]])

In [212]:
A

tensor([[-4., -3., -2.],
        [-1.,  0.,  1.],
        [ 2.,  3.,  4.],
        [ 5.,  6.,  7.]])

In [213]:
relu = torch.nn.ReLU()
result = relu(A)

In [214]:
result - 0.5

tensor([[-0.5000, -0.5000, -0.5000],
        [-0.5000, -0.5000,  0.5000],
        [ 1.5000,  2.5000,  3.5000],
        [ 4.5000,  5.5000,  6.5000]])

#### Linear Layer

In [241]:
#| export
def test_intialize_parameters_should_return_true():
    
    m = 5 # number of rows
    nh = 3 # number of hidden layers
    w1, b1, w2, b2 = initialize_parameters(m=m, nh=nh)
    assert w1.shape == (m, nh)
    assert b1.shape == (nh,)
    assert w2.shape == (nh, 1)
    assert b2.shape == (1,)

In [242]:
#| export
def test_linear_should_return_true():
    pass

In [247]:
#| export
def test_linear_gradient_should_return_true():
    pass