In [2]:
#| default_exp loss

# Loss functions

> A simple API for creating and using playing cards

In [3]:
#| export
from fastcore.utils import *
import numpy as np

In [ ]:
#| export
from tinypytorch.core import *

In [22]:
#| hide
from nbdev.showdoc import *
from fastcore.test import *

### Mean Square Error

In [3]:
# #| export
# def mse(output, targ):
#     return (output.squeeze(-1) - targ).pow(2).mean()

In [4]:
# #| export
# class MSE():
#     def __call__(self, inp, targ):
#         self.inp = inp
#         self.targ = targ
#         self.out = (inp.squeeze() - targ).pow(2).mean()
#         return self.out
    
#     def backward(self):
#         self.inp.g = 2. * (self.inp.squeeze() - self.targ).unsqueeze(-1) / self.targ.shape[0]

### Cross-Entropy Loss

#### Softmax



$\sigma(\mathbf{z})_{i}=\frac{e^{z_{i}}}{\sum_{j=1}^{K} e^{z_{j}}}$

In [6]:
#| export
def softmax(x):
    pass
    #return np.exp(x) / np.exp(x).sum()

In [24]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
softmax(A)

array([[0.00426978, 0.01160646, 0.03154963],
       [0.08576079, 0.23312201, 0.63369132]])

#### Log Softmax

In [29]:
#| export
def log_softmax(x):
    #sm = softmax(x)
    #return np.log(sm)
    pass

In [30]:
log_softmax(A)

array([[-5.45619332, -4.45619332, -3.45619332],
       [-2.45619332, -1.45619332, -0.45619332]])

#### Negative Log-Likelihood

In [33]:
#| export
def negative_log_likelihood(
    input, # the probabilities predicted for each label
    target: 'the index of the correct label'):
    pass