In [71]:
import torch
import torch.nn.functional as F

from tinypytorch.data import get_local_data
from tinypytorch.model import Linear, CrossEntropy, log_softmax
from tinypytorch.metrics import accuracy

In [72]:
#| hide
from tinypytorch.core import *

# tinypytorch

> A tiny version of pytorch from scratch

Dependence libraries
- nbdev
- torch
- matplotlib
- pytest

This file will become your README and also the index of your documentation.

## Install

```sh
pip install tinypytorch
```

### Train a neural network

#### Data

In [79]:
x_train, y_train, x_valid, y_valid = get_local_data()

In [80]:
x_train.shape, y_train.shape

(torch.Size([50000, 784]), torch.Size([50000]))

#### Initialize hyperparameters

In [81]:
x_train.shape, y_train.shape

(torch.Size([50000, 784]), torch.Size([50000]))

In [82]:
x_valid.shape, y_valid.shape

(torch.Size([10000, 784]), torch.Size([10000]))

In [83]:
n, m = x_train.shape # num examples and pixels

In [84]:
n, m

(50000, 784)

In [85]:
nh = 50 # num hidden

- Training set's shape: (50000, 784)
- Weight's shape: (784, 50)
- Bias's shape: (50)

#### The first layer (Lin): (50000, 784) x (784, 50) + (50)

In [86]:
bs = 64

In [87]:
xb = x_train[0:bs]

In [88]:
yb = y_train[0:bs]

In [89]:
linear = Linear(784, 50, 10)

In [90]:
loss_func = CrossEntropy(debug=True)

In [91]:
preds = linear(xb)

Model.__call__
l=<tinypytorch.model.Lin object at 0x7f7a288b2c70>
Lin.forward
inp=torch.Size([64, 784])
w=torch.Size([784, 50])
b=torch.Size([50])
output.shape=torch.Size([64, 50])
x.shape=torch.Size([64, 50])
Model.__call__
l=<tinypytorch.model.ReLU object at 0x7f7a3997ff10>
x.shape=torch.Size([64, 50])
Model.__call__
l=<tinypytorch.model.Lin object at 0x7f7a3996ea60>
Lin.forward
inp=torch.Size([64, 50])
w=torch.Size([50, 10])
b=torch.Size([10])
output.shape=torch.Size([64, 10])
x.shape=torch.Size([64, 10])


In [92]:
preds.shape, yb.shape

(torch.Size([64, 10]), torch.Size([64]))

In [93]:
yb.shape[0]

64

In [96]:
preds.shape

torch.Size([64, 10])

In [97]:
yb.shape

torch.Size([64])

In [ ]:
preds.shape

In [101]:
preds[range(yb.shape[0]), yb]

tensor([-0.7899, -0.2244,  0.5587, -0.5513,  0.6729,  0.5547, -1.0991,  0.0171,
        -1.0548,  1.0696,  0.0562, -0.3426,  0.2353, -0.0590, -1.0906,  0.6658,
         0.6518, -0.3516,  0.2089,  0.5815,  0.7556, -0.3573,  0.4235, -0.6379,
        -0.5622,  0.7301,  0.3195, -0.0420,  0.9286,  0.2867, -0.6922, -0.6086,
         0.1102,  0.3287, -0.3519, -0.4250,  0.0212, -0.0791,  0.0784,  0.5390,
        -1.0017, -0.4754, -0.1867,  0.6183,  0.0220,  0.4119, -0.2202, -0.8514,
         0.9460,  0.0112, -0.3195, -0.2681,  0.2008,  0.7524,  0.2217, -0.4809,
        -0.6313,  0.8462,  0.8521, -0.7270, -0.1289,  0.5712,  0.0120,  0.1694])

In [102]:
preds.shape, yb.shape

(torch.Size([64, 10]), torch.Size([64]))

In [103]:
preds

tensor([[-3.0960e-01, -7.0857e-01,  1.0105e+00,  8.8069e-02,  2.5577e-02,
         -7.8985e-01,  6.3253e-01,  1.2197e-01,  4.3733e-01,  6.4537e-01],
        [-2.2442e-01, -7.2033e-01,  1.0677e+00, -2.9689e-01,  2.3297e-01,
         -8.9722e-01,  1.3153e-01,  4.1701e-02,  2.4915e-02,  8.6007e-02],
        [-4.6453e-01, -6.9876e-01,  4.3695e-01, -7.0212e-01,  5.5870e-01,
         -3.3413e-01,  2.4599e-01,  1.4059e-01,  4.5189e-01,  2.2579e-01],
        [-4.3171e-01, -5.5132e-01,  5.2756e-01, -4.1145e-01,  1.5057e-01,
         -4.9821e-01,  7.1354e-02,  1.0099e-01, -8.1487e-02,  1.9316e-01],
        [-8.3915e-01, -1.1443e+00,  9.4532e-01, -1.1813e-01,  9.4655e-01,
         -1.0483e+00, -1.8421e-01,  3.1190e-02, -3.4057e-01,  6.7287e-01],
        [-3.9944e-01, -3.6781e-01,  5.5475e-01, -5.4254e-01, -1.6361e-01,
         -1.7875e-01,  3.9308e-01,  2.3740e-01, -5.6544e-01, -5.2972e-01],
        [-4.0743e-01, -1.0991e+00,  1.0513e+00, -5.1571e-01,  1.1972e+00,
         -8.1583e-01,  1.5867e-0

In [104]:
sm_pred = log_softmax(preds)

In [105]:
sm_pred.shape

torch.Size([64, 10])

In [106]:
sm_pred

tensor([[-2.8755, -3.2745, -1.5554, -2.4778, -2.5403, -3.3557, -1.9334, -2.4439,
         -2.1286, -1.9205],
        [-2.6137, -3.1096, -1.3216, -2.6862, -2.1563, -3.2865, -2.2577, -2.3476,
         -2.3644, -2.3033],
        [-2.8522, -3.0864, -1.9507, -3.0898, -1.8290, -2.7218, -2.1417, -2.2471,
         -1.9358, -2.1619],
        [-2.7006, -2.8202, -1.7413, -2.6803, -2.1183, -2.7671, -2.1975, -2.1679,
         -2.3503, -2.0757],
        [-3.2966, -3.6017, -1.5121, -2.5756, -1.5109, -3.5057, -2.6416, -2.4262,
         -2.7980, -1.7846],
        [-2.6270, -2.5954, -1.6728, -2.7701, -2.3912, -2.4063, -1.8345, -1.9902,
         -2.7930, -2.7573],
        [-3.0354, -3.7271, -1.5766, -3.1437, -1.4307, -3.4438, -2.4693, -2.7279,
         -2.7930, -1.6308],
        [-2.0834, -2.7195, -1.7641, -2.4535, -2.3592, -2.7189, -2.0202, -2.6872,
         -2.3811, -2.3159],
        [-3.1867, -3.6091, -1.5912, -3.2928, -1.4303, -3.2588, -2.3590, -2.7260,
         -2.6761, -1.6913],
        [-3.3102, -

In [107]:
F.nll_loss(preds, yb)

tensor(-0.0128)

In [109]:
loss = loss_func(preds, yb)

pred.shape=torch.Size([64, 10])
sm_pred.shape=torch.Size([64, 10])
inp.shape=torch.Size([64, 10])
targ.shape=torch.Size([64])


In [110]:
loss

tensor(2.4523)